### ISSUE TITLE
Can't use "." dot char in last URL variable

### ISSUE THREAD

**Issue by blackarcanis** [handcraftedinthealps/RestRoutingBundle#12]
Hi !
Thank you for your work here. Still trying to migrate from FOSRESTBundle 2.x to 3.x

Currently having an issue with a variable in my URL. Here it is:
` @Get("/myjob/{job}/subjob/{sub}")`

Using your bundle to generate the route, is not allowing for {sub} to have a "." according to the regex generated (eg. "test.toto"):
`[^\/\\.]++`

Any idea why ? Not the same regex is generated for the variable {job}:
`[^\/]++` (and it's fine for this one)

Thank you !

EDIT: no issue with FOSRESTBundle 2.x (I can use "." in URL variable at the end of an URL).

**Comment by alexander-schranz** [comment]
@blackarcanis the `GET` annotation is not handled by this bundle. This bundle handles the `type: rest` routes and generate automatic routes per Action function. @Get should be handled by symfony route generator. And the requirements you should be able to be set there by provide the `requirements` option to your `GET` function: https://symfony.com/doc/current/routing.html#parameters-validation

**Comment by blackarcanis** [comment]
@alexander-schranz Thank you. And yes you are right, I will use `@Route` annotation instead with the good `requirements`.
