### ISSUE TITLE
Deprecated warnings with PHP 8

### ISSUE THREAD

**Issue by kevinpapst** [handcraftedinthealps/RestRoutingBundle#13]
Hi,

With PHP 8 the method [ReflectionParameter::getClass()](https://www.php.net/manual/de/reflectionparameter.getclass.php) is deprecated and can be replaced by [ReflectionParameter::getType()](https://www.php.net/manual/de/reflectionparameter.gettype.php).

I am getting a lot of deprecations [caused by this code](https://github.com/handcraftedinthealps/RestRoutingBundle/blob/master/Routing/Loader/Reader/RestActionReader.php#L430):
<img width="1115" alt="Bildschirmfoto 2021-06-04 um 12 04 01" src="https://user-images.githubusercontent.com/533162/120785012-ff74a700-c52c-11eb-86ce-b88e60ed9862.png">
 
@alexander-schranz As this bundle requires PHP 7.2 and `ReflectionParameter::getType()` is available since 7.1, we should be able to safely change the code, correct?

**Comment by alexander-schranz** [comment]
I'm not familiar enough with the differences but as you described it it should be save to be replaced. Do you want to create a PR for it?
