### ISSUE TITLE
Wrong package name

### ISSUE THREAD

**Issue by MaximumRGB** [handcraftedinthealps/RestRoutingBundle#5]
Docs file named `1-setting_up_the_bundle.rst` contains a command to download the latest stable version of the bundle, but the package name `friendsofsymfony/rest-routing-bundle` seems to be wrong, couse i get an error message `The requested package friendsofsymfony/rest-routing-bundle could not be found in any version, there may be a typo in the package name.` But if i change the package name to `handcraftedinthealps/rest-routing-bundle`, then everything goes ok.

**Comment by alexander-schranz** [comment]
@MaximumRGB Thank you for your report. Do you want to create a PR?

**Comment by MaximumRGB** [comment]
Created a pull request with fixes of docs.
